clean workbooks and add requirements
1. add `requirements.txt` per chapter to indicate the minimal packages the notebook requires, run them on a linux desktop to ensure they work well.
2. add a function to automatically download data.
3. replace `numpy.matrix` with `np.array`:
    1. `np.matrix` usage is deprecated in 1.0 and will raise a TypeError in 1.2. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
    2. change matrix multiplication: `a*b` to `a@b`.
4. remove `demjson` — it often reports errors when using python ≥ 3.0, using `eval` instead.
5. Chapter 5 & 10: [TODO]: fix `implicit` error:

    ```latex
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    /tmp/ipykernel_2995/3321745298.py in <module>
    ----> 1 model.fit(Xiu)

    ~/anaconda3/envs/pml/lib/python3.7/site-packages/implicit/gpu/bpr.py in fit(self, user_items, show_progress)
         88
         89         # We need efficient user lookup for case of removing own likes
    ---> 90         if not user_items.has_sorted_indices:
         91             user_items.sort_indices()
         92

    ~/anaconda3/envs/pml/lib/python3.7/site-packages/scipy/sparse/base.py in __getattr__(self, attr)
        685             return self.getnnz()
        686         else:
    --> 687             raise AttributeError(attr + " not found")
        688
        689     def transpose(self, axes=None, copy=False):

    AttributeError: has_sorted_indices not found
    ```

6. Chapter 6: `fastFM` cannot support python ≥ 3.7(many issues reported by students last year), rewrite using `pyFM` instead, which is similar to `sklearn`. The plot of `performance vs. item coolness` is updated accordingly, and looks more reasonable.
7. Chapter 7: [TODO]: replace `fastFM` with `pyFM` .